# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.1.0
maven_group = moe.qbyte.movement_plus
archives_name = movement_plus
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.11

# Mappings
parchment_version = 2025.12.20

# Dependencies
architectury_api_version = 19.0.1
forge_config_api_port_version = 21.11.1

# Dev environment
mod_menu_version = 17.0.0
fabric_loader_version = 0.19.3
fabric_api_version = 0.141.5+1.21.11
neoforge_version = 21.11.44
