# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
ssueTrackerURL="https://github.com/Necr0/Coyote-Lib/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="coyotelib"
version="${file.jarVersion}"
displayName="CoyoteLib"
# updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/coyotelib"
logoFile="coyotelib.png"
credits="Thanks to the Forge Team, the Forge Discord Channel, and the MMD Discord Channel."

authors="Necro"
description='''
A library mod providing things like a double jump and coyote time API that for mods to tap into. It also provides a customizable debug overlay and custom gamerules.
'''

[[dependencies.coyotelib]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.coyotelib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
