modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Necr0/Coyote-Lib/issues"

[[mods]]
modId="coyotelib"
version="${file.jarVersion}"
displayName="CoyoteLib"
updateJSONURL="https://gist.githubusercontent.com/Necr0/22a14ea04a63b0b1fe1484c46fb6786a/raw/coyotelib_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/coyotelib"
logoFile="coyotelib.png"
credits="Thanks to the Forge Team, the Forge Discord Channel, and the MMD Discord Channel."

authors="Necro"
description='''
A library mod providing things like a double jump and coyote time API that for mods to tap into. It also provides a customizable debug overlay and custom gamerules.
'''

[[dependencies.coyotelib]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.coyotelib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
