modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/QbDesu/MovementPlus/issues"
license="Unlicense"

[[mods]]
modId="movement_plus"
version="${file.jarVersion}"
displayName="Movement Plus"
updateJSONURL="https://gist.githubusercontent.com/QbDesu/22a14ea04a63b0b1fe1484c46fb6786a/raw/movement_plus_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/movement_plus"
logoFile="movement_plus.png"
credits="Thanks to the Forge Team, the Forge Discord Channel, and the MMD Discord Channel."

authors="Qb"
description='''
A mod that allows for configurable movement such as midair jumps.
'''

[[dependencies.movement_plus]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.movement_plus]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"