modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/QbDesu/CoyoteLib/issues"
license="Unlicense"

[[mods]]
modId="coyotelib"
version="${file.jarVersion}"
displayName="CoyoteLib"
updateJSONURL="https://gist.githubusercontent.com/QbDesu/22a14ea04a63b0b1fe1484c46fb6786a/raw/coyotelib_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/coyotelib"
logoFile="coyotelib.png"
credits="Thanks to the Forge Team, the Forge Discord Channel, and the MMD Discord Channel."

authors="Qb"
description='''
A library mod providing things like a double jump and coyote time API that for mods to tap into. It also provides a customizable debug overlay and custom gamerules.
'''

[[dependencies.coyotelib]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.coyotelib]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"