modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ModdingPlus/MovementPlus/issues"
license = "Unlicense"

[[mods]]
modId = "movement_plus"
version = "${version}"
displayName = "Movement Plus"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/movement_plus"
authors = "Qb"
description = '''
A mod that allows for configurable movement such as midair jumps.
'''
logoFile = "assets/movement_plus/logo.png"

[[dependencies.movement_plus]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.movement_plus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.21.12)"
ordering = "NONE"
side = "BOTH"

[[dependencies.movement_plus]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "movement_plus.mixins.json"
